# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp', models.CharField(max_length=100)),
                ('outp', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000000)),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 11, 7, 2, 20, 11, 757266, tzinfo=utc))),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
