# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
